Repository iamprovidence/Coursework, pull requests merged in 2019-02, with the labels that each got.

#128 Feature/data access tests. Close#12, Close#17
  Project/Core/Configuration/DBConfig.cs
  Project/DataAccess/Configuration/PhotoConfiguration.cs
  Project/DataAccess/Context/AppContext.cs
  Project/DataAccess/Repositories/PhotoRepository.cs
  Project/DataAccess/Repositories/UserRepository.cs
  Project/UnitTest/DataAccess/Context/AppContextTest.cs
  Project/UnitTest/DataAccess/Entities/CommentLikeTest.cs
  Project/UnitTest/DataAccess/Entities/CommentTest.cs
  Project/UnitTest/DataAccess/Entities/MessageTest.cs
  Project/UnitTest/DataAccess/Entities/PhotoLikeTest.cs
  Project/UnitTest/DataAccess/Entities/PhotoTest.cs
  Project/UnitTest/DataAccess/Entities/SubjectTest.cs
  Project/UnitTest/DataAccess/Entities/UserTest.cs
  Project/UnitTest/DataAccess/Repositories/CommentLikeRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/CommentRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/GenericRepositoriesTest.cs
  Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoLikeRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/UserRepositoryTest.cs
  Project/UnitTest/Resources/Classes/DbFiller.cs
  Project/UnitTest/Resources/DataAccess/Repositories/AvatarFormat.xml
  Project/UnitTest/Resources/DataAccess/Repositories/WrongAvatarPathOrExtension.xml
  Project/UnitTest/Resources/DataAccess/Repositories/WrongLengthNameOrPassword.xml
  Project/UnitTest/Resources/DataAccess/Repositories/WrongPhotoExtension.xml
  Project/UnitTest/Resources/DataAccess/Repositories/WrongPhotoPath.xml
  Project/UnitTest/UnitTest.csproj
Labels: aim

#132 Feature/comunity profile close#126
  .editorconfig
  .gitattributes
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/empty_template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/design_pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/short_pull_request_template.md
  .travis.yml
  README.md
Labels: enhancement

#135 Set up that one instance of the application can be run at once. Close#87.
  Project/Galagram/App.xaml.cs
Labels: enhancement

#146 Hotfix int to Guid in tests.
  Project/Galagram/ViewModel/Commands/Registration/LogInCommand.cs
  Project/UnitTest/DataAccess/Repositories/CommentRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/UserRepositoryTest.cs
  Project/UnitTest/UnitTest.csproj
  Project/UnitTest/ViewModel/ViewModels/RegistrationViewModelTest.cs
  Project/UnitTest/ViewModel/ViewModels/User/AskQuestionViewModelTest.cs
  Project/UnitTest/ViewModel/ViewModels/User/FollowViewModelTest.cs
  Project/UnitTest/ViewModel/ViewModels/User/MainWindowViewModelTest.cs
  Project/UnitTest/ViewModel/ViewModels/User/PhotoInsideViewModeltest.cs
  Project/UnitTest/ViewModel/ViewModels/User/SearchViewModelTest.cs
  Project/UnitTest/ViewModel/ViewModels/User/SettingViewModelTest.cs
Labels: aim, bug

#148 Fix/random fill
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  Project/Core/Exceptions/ComparingException.cs
  Project/Core/Messages/Error/Exceptions.cs
  Project/Core/Messages/Info/Admin.cs
  Project/DataAccess/Comparers/SubjectComparer.cs
  Project/DataAccess/Comparers/UserComparer.cs
  Project/DataAccess/DataAccess.csproj
  Project/DataAccess/Entities/Comment.cs
  Project/DataAccess/Entities/LikeBase.cs
  Project/DataAccess/Entities/Message.cs
  Project/DataAccess/Entities/Photo.cs
  Project/DataAccess/Entities/Subject.cs
  Project/DataAccess/Entities/User.cs
  Project/DataAccess/Enums/Comparers/UserCompareType.cs
  Project/DataAccess/Enums/EntityStringFormat.cs
  Project/DataAccess/Interfaces/IRepository.cs
  Project/DataAccess/Repositories/GenericRepository.cs
  Project/DataAccess/Repositories/NonGenericRepository.cs
  Project/Galagram/App.xaml.cs
  Project/Galagram/Converters/ReverseBooleanConverter.cs
  Project/Galagram/Window/User/AskQuestion.xaml
  Project/Galagram/Window/User/Follow.xaml
  Project/Galagram/Window/User/Search.xaml
  Project/Galagram/Window/User/Setting.xaml
  Project/UnitTest/Resources/Classes/DbFiller.cs
  Project/UnitTest/Resources/Initializers/DatabaseInitializer.cs
Labels: bug, optimization

#149 Make entities equatable Close#129
  Project/ConsoleTest/Program.cs
  Project/DataAccess/Entities/EntityBase.cs
  Project/UnitTest/DataAccess/Context/AppContextTest.cs
Labels: enhancement

#150 Set up to clear log file if it is big enough. Close#101.
  Project/Core/Configuration/AppConfig.cs
  Project/Core/Converters/FileSizeConverter.cs
  Project/Core/Core.csproj
  Project/Core/Enums/FileSizeMode.cs
  Project/Core/Logger.cs
Labels: aim

#155 Add reference to lib close #136
  .travis.yml
  Project/DataAccess/DataAccess.csproj
  Project/Galagram/Galagram.csproj
  Project/UnitTest/UnitTest.csproj
  appveyor.yml
Labels: bug

#154 Fix/iss#142
  Project/DataAccess/Repositories/GenericRepository.cs
  Project/Galagram/Services/NavigationManager.cs
  Project/Galagram/ViewModel/Commands/Admin/DeleteItem/DeleteItemCommand.cs
  Project/Galagram/ViewModel/Commands/Admin/Subject/Single/CreateUpdateCommand.cs
  Project/Galagram/ViewModel/Commands/Admin/UpdateCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/LogOutCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowersListCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowingListCommand.cs
  Project/Galagram/ViewModel/ViewModel/Admin/Comments/SingleViewModel.cs
  Project/Galagram/ViewModel/ViewModel/User/FollowViewModel.cs
Labels: bug, optimization

#151 Test mode for DB. close#131
  Project/Core/Configuration/AppConfig.cs
  Project/Core/Configuration/TestConfig.cs
  Project/Core/Core.csproj
  Project/Core/Enums/DataBaseFillMode.cs
  Project/UnitTest/DataAccess/Context/AppContextTest.cs
  Project/UnitTest/DataAccess/Entities/CommentLikeTest.cs
  Project/UnitTest/DataAccess/Entities/CommentTest.cs
  Project/UnitTest/DataAccess/Entities/MessageTest.cs
  Project/UnitTest/DataAccess/Entities/PhotoLikeTest.cs
  Project/UnitTest/DataAccess/Entities/PhotoTest.cs
  Project/UnitTest/DataAccess/Entities/SubjectTest.cs
  Project/UnitTest/DataAccess/Entities/UserTest.cs
  Project/UnitTest/DataAccess/Repositories/CommentLikeRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/CommentRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoLikeRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/UserRepositoryTest.cs
  Project/UnitTest/Resources/Classes/DbFiller.cs
  Project/UnitTest/Resources/Initializers/DatabaseInitializer.cs
  Project/UnitTest/UnitTest.csproj
Labels: enhancement

#156 Projects info Close#88
  Project/ConsoleTest/Properties/AssemblyInfo.cs
  Project/Core/Properties/AssemblyInfo.cs
  Project/DataAccess/Properties/AssemblyInfo.cs
  Project/Galagram/Properties/AssemblyInfo.cs
  Project/UnitTest/Properties/AssemblyInfo.cs
Labels: enhancement

#152 Set up enum flags and On/Off for options from LogMode. Close#67, Close#89.
  Project/Core/Configuration/AppConfig.cs
  Project/Core/LogMode.cs
  Project/Core/Logger.cs
Labels: enhancement

#157 Feature/rework comment section
  Project/DataAccess/DataAccess.csproj
  Project/DataAccess/Entities/Comment.cs
  Project/DataAccess/Wrappers/CommentWrapper.cs
  Project/DataAccess/Wrappers/PhotoWrapper.cs
  Project/Galagram/Converters/CommentCollectionToLengthConverter.cs
  Project/Galagram/Galagram.csproj
  Project/Galagram/Theme/Resources/Converters.xaml
  Project/Galagram/Theme/User/Pincky/Styles/Buttons.xaml
  Project/Galagram/Theme/User/Pincky/Styles/Collections.xaml
  Project/Galagram/Theme/User/Pincky/Templates/Collections.xaml
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowPhotoCommand.cs
  Project/Galagram/ViewModel/Commands/User/PhotoInside/DeleteCommentCommand.cs
  Project/Galagram/ViewModel/Commands/User/PhotoInside/LikeCommentCommand.cs
  Project/Galagram/ViewModel/Commands/User/PhotoInside/LikePhotoCommand.cs
  Project/Galagram/ViewModel/Commands/User/PhotoInside/WriteCommentCommand.cs
  Project/Galagram/ViewModel/ViewModel/User/MainWindowViewModel.cs
  Project/Galagram/ViewModel/ViewModel/User/PhotoInsideViewModel.cs
  Project/Galagram/Window/User/PhotoInside.xaml
Labels: optimization

#163 Equals entity test. close#160
  Project/DataAccess/Entities/EntityBase.cs
  Project/DataAccess/Entities/Message.cs
  Project/DataAccess/Entities/Subject.cs
  Project/UnitTest/DataAccess/Entities/CommentLikeTest.cs
  Project/UnitTest/DataAccess/Entities/CommentTest.cs
  Project/UnitTest/DataAccess/Entities/MessageTest.cs
  Project/UnitTest/DataAccess/Entities/PhotoLikeTest.cs
  Project/UnitTest/DataAccess/Entities/PhotoTest.cs
  Project/UnitTest/DataAccess/Entities/SubjectTest.cs
  Project/UnitTest/DataAccess/Entities/UserTest.cs
Labels: aim

#159 Generic DB clearing. Close#138
  Project/Core/Configuration/TestConfig.cs
  Project/UnitTest/DataAccess/Repositories/CommentLikeRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/CommentRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoLikeRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/UserRepositoryTest.cs
  Project/UnitTest/Resources/Classes/DbFiller.cs
  Project/UnitTest/Resources/Initializers/DatabaseInitializer.cs
Labels: invalid

#165 Delete user account. Close#56
  Project/Core/Core.csproj
  Project/Core/Logger.cs
  Project/Core/Messages/Info/Admin.cs
  Project/Core/Messages/Info/ViewModel/Command/User/Setting/ApplyChanges.cs
  Project/Core/Messages/Info/ViewModel/Command/User/Setting/RemoveAccount.cs
  Project/Galagram/Galagram.csproj
  Project/Galagram/Services/WindowManager.cs
  Project/Galagram/Theme/User/Pincky/Styles/Buttons.xaml
  Project/Galagram/ViewModel/Commands/User/MainWindow/LogOutCommand.cs
  Project/Galagram/ViewModel/Commands/User/Setting/RemoveAccountCommand.cs
  Project/Galagram/ViewModel/ViewModel/User/MainWindowViewModel.cs
  Project/Galagram/ViewModel/ViewModel/User/SettingViewModel.cs
  Project/Galagram/Window/User/Setting.xaml
Labels: aim

#162 Show follower/following amount. Close#95
  Project/Core/Configuration/AppConfig.cs
  Project/DataAccess/Context/AppContext.cs
  Project/Galagram/App.xaml.cs
  Project/Galagram/Converters/IntToStringConverter.cs
  Project/Galagram/Galagram.csproj
  Project/Galagram/Theme/Resources/Converters.xaml
  Project/Galagram/Theme/Resources/Values.xaml
  Project/Galagram/ViewModel/Commands/User/MainWindow/FollowCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowListCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowingListCommand.cs
  Project/Galagram/ViewModel/ViewModel/User/FollowViewModel.cs
  Project/Galagram/ViewModel/ViewModel/User/MainWindowViewModel.cs
  Project/Galagram/Window/User/Follow.xaml
  Project/Galagram/Window/User/MainWindow.xaml
  Project/UnitTest/App.config
  Project/UnitTest/DataAccess/Repositories/CommentRepositoryTest.cs
Labels: design, enhancement, invalid, optimization

#167 Reverse drop box
  Project/Galagram/Theme/User/Pincky/Styles/Collections.xaml
  Project/Galagram/Window/User/MainWindow.xaml
Labels: enhancement

#168 Add opportunity to log DataBase Close#158. fix test deleting close#166
  Project/Core/LogMode.cs
  Project/DataAccess/Context/UnitOfWork.cs
  Project/Galagram/App.xaml.cs
  Project/UnitTest/Resources/Classes/DbFiller.cs
Labels: bug, enhancement

#171 Make folder hidden. close#49
  Project/Core/Configuration/AppConfig.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/UploadPhotoCommand.cs
  Project/Galagram/ViewModel/Commands/User/Setting/ApplyChangesCommand.cs
Labels: aim

#172 faster DB removing close#123
  Project/DataAccess/Context/AppContext.cs
Labels: optimization

#173 Stroke for comments close#108
  Project/Galagram/Theme/User/Pincky/Styles/Collections.xaml
  Project/Galagram/Theme/User/Pincky/Templates/Collections.xaml
Labels: design, enhancement

#170 Reverse photo order. Close#76
  Project/Galagram/Collections/ReverseCollection.cs
  Project/Galagram/Galagram.csproj
  Project/Galagram/ViewModel/Commands/User/MainWindow/SettingCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowListCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowPhotoCommand.cs
  Project/Galagram/ViewModel/ViewModel/User/MainWindowViewModel.cs
  Project/Galagram/Window/User/MainWindow.xaml
Labels: design, enhancement

#177 Make value isn't changed without saving. Close#153.
  Project/Galagram/ViewModel/Commands/Admin/GoBackCommand.cs
  Project/Galagram/Window/Admin/UserControls/Comments/Single.xaml
  Project/Galagram/Window/Admin/UserControls/Messages/Single.xaml
  Project/Galagram/Window/Admin/UserControls/Photo/Single.xaml
  Project/Galagram/Window/Admin/UserControls/Subjects/Single.xaml
  Project/Galagram/Window/Admin/UserControls/Users/Single.xaml
Labels: bug

#176 Generic OpenProfile Command close#83
  Project/Galagram/Galagram.csproj
  Project/Galagram/ViewModel/Commands/User/Follow/DeleteFollowCommand.cs
  Project/Galagram/ViewModel/Commands/User/Follow/OpenProfileCommand.cs
  Project/Galagram/ViewModel/Commands/User/OpenProfileCommand.cs
  Project/Galagram/ViewModel/Commands/User/Search/SearchCommand.cs
  Project/Galagram/ViewModel/ViewModel/User/FollowViewModel.cs
  Project/Galagram/ViewModel/ViewModel/User/OpenProfileViewModelBase.cs
  Project/Galagram/ViewModel/ViewModel/User/SearchViewModel.cs
  Project/Galagram/Window/User/Follow.xaml
Labels: optimization

#178 Implement ReverseCollection and UnitTest for it. close#169
  Project/Galagram/Collections/ReverseCollection.cs
  Project/UnitTest/Resources/View/Collections/ReverseCollection/IndexerValueSet.xml
  Project/UnitTest/Resources/View/Collections/ReverseCollection/ThreeRandomItem.xml
  Project/UnitTest/Resources/View/Collections/ReverseCollection/WrongIndex.xml
  Project/UnitTest/UnitTest.csproj
  Project/UnitTest/View/Collections/ReverseCollectionTest.cs
Labels: aim

#182 Ban user for spam. Close#105, Close#180
  Project/DataAccess/Entities/User.cs
  Project/Galagram/ViewModel/Commands/User/AskQuestion/AskCommand.cs
  Project/Galagram/ViewModel/ViewModel/Admin/User/AllViewModel.cs
  Project/Galagram/ViewModel/ViewModel/Admin/User/SingleViewModel.cs
  Project/Galagram/Window/Admin/UserControls/Users/All.xaml
  Project/Galagram/Window/Admin/UserControls/Users/Single.xaml
Labels: aim, bug, design

#183 NonGenericRepository. close#139
  Project/DataAccess/Repositories/NonGenericRepository.cs
  Project/UnitTest/DataAccess/Repositories/NonGenericRepositorySubjectTest.cs
  Project/UnitTest/UnitTest.csproj
Labels: aim

#187 Fix normal work with constraints in Admin Part. Close#144, Close#185.
  Project/Core/Configuration/TestConfig.cs
  Project/Core/Enums/DataBaseFillMode.cs
  Project/Core/Messages/Info/Admin.cs
  Project/Core/Messages/Info/ViewModel/Command/User/Setting/RemoveAccount.cs
  Project/DataAccess/Wrappers/CommentWrapper.cs
  Project/Galagram/Galagram.csproj
  Project/Galagram/Properties/AssemblyInfo.cs
  Project/Galagram/Services/NavigationManager.cs
  Project/Galagram/Theme/AdminPanel/Classic/Styles/Buttons.xaml
  Project/Galagram/ViewModel/CommandBase.cs
  Project/Galagram/ViewModel/Commands/Admin/Comment/Single/ValidateCommand.cs
  Project/Galagram/ViewModel/Commands/Admin/MultipleCommand.cs
  Project/Galagram/ViewModel/Commands/Admin/Subject/Single/CreateUpdateCommand.cs
  Project/Galagram/ViewModel/Commands/Admin/UpdateCommand.cs
  Project/Galagram/ViewModel/Commands/Admin/User/Single/ValidateCommand.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowListCommand.cs
  Project/Galagram/ViewModel/Commands/User/PhotoInside/WriteCommentCommand.cs
  Project/Galagram/ViewModel/Commands/User/Setting/ApplyChangesCommand.cs
  Project/Galagram/ViewModel/Enums/Admin/CommandState.cs
  Project/Galagram/ViewModel/ViewModel/Admin/Comments/SingleViewModel.cs
  Project/Galagram/ViewModel/ViewModel/Admin/Subject/SingleViewModel.cs
  Project/Galagram/ViewModel/ViewModel/Admin/User/SingleViewModel.cs
  Project/Galagram/ViewModel/ViewModel/User/SettingViewModel.cs
  Project/Galagram/Window/Admin/UserControls/Comments/Single.xaml
  Project/UnitTest/DataAccess/Context/AppContextTest.cs
  Project/UnitTest/DataAccess/Repositories/CommentLikeRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs
  Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs
  Project/UnitTest/Properties/AssemblyInfo.cs
  Project/UnitTest/Resources/Classes/DbFiller.cs
Labels: aim, bug

#188 Reworked adding photo algorithm. close#184
  Project/Core/Configuration/AppConfig.cs
  Project/DataAccess/Repositories/UserRepository.cs
  Project/Galagram/ViewModel/Commands/User/MainWindow/UploadPhotoCommand.cs
Labels: invalid

#190 Change design for PhotoInsideWindow close#94
  Project/DataAccess/Repositories/PhotoLikeRepository.cs
  Project/Galagram/Theme/User/Pincky/Styles/Buttons.xaml
  Project/Galagram/ViewModel/Commands/User/PhotoInside/LikePhotoCommand.cs
  Project/Galagram/ViewModel/ViewModel/User/PhotoInsideViewModel.cs
  Project/Galagram/Window/User/PhotoInside.xaml
  Project/UnitTest/DataAccess/Context/AppContextTest.cs
  Project/UnitTest/DataAccess/Repositories/PhotoLikeRepositoryTest.cs
  Project/UnitTest/Resources/Classes/DbFiller.cs
Labels: design, invalid

#191 Add silver background to photo. close#179
  Project/DataAccess/Entities/EntityBase.cs
  Project/Galagram/Window/Admin/UserControls/Comments/Single.xaml
  Project/Galagram/Window/Admin/UserControls/Photo/Single.xaml
  Project/Galagram/Window/Admin/UserControls/Users/Single.xaml
Labels: bug fix, design

#192 Remove photo from server close#181
  Project/Core/Configuration/AppConfig.cs
  Project/Galagram/Galagram.csproj
  Project/Galagram/Theme/AdminPanel/Classic/Templates/Collections.xaml
  Project/Galagram/Theme/User/Pincky/Templates/Collections.xaml
  Project/Galagram/ViewModel/CommandBase.cs
  Project/Galagram/ViewModel/Commands/Admin/User/Single/ValidateCommand.cs
  Project/Galagram/ViewModel/Commands/MultipleCommand.cs
  Project/Galagram/ViewModel/Commands/RelayCommand.cs
  Project/Galagram/ViewModel/Commands/Shared/DeleteAvatarFromServerCommand.cs
  Project/Galagram/ViewModel/Commands/Shared/DeletePhotoFolderCommand.cs
  Project/Galagram/ViewModel/Commands/Shared/DeletePhotoFromServerCommand.cs
  Project/Galagram/ViewModel/Commands/User/Setting/ApplyChangesCommand.cs
  Project/Galagram/ViewModel/Commands/User/Setting/RemoveAccountCommand.cs
  Project/Galagram/ViewModel/ViewModel/Admin/AllItemViewModelBase.cs
  Project/Galagram/ViewModel/ViewModel/Admin/Comments/SingleViewModel.cs
  Project/Galagram/ViewModel/ViewModel/Admin/Photo/SingleViewModel.cs
  Project/Galagram/ViewModel/ViewModel/Admin/User/AllViewModel.cs
  Project/Galagram/ViewModel/ViewModel/Admin/User/SingleViewModel.cs
  Project/Galagram/ViewModel/ViewModel/User/SettingViewModel.cs
Labels: bug fix
